In [1]:
import pandas as pd

In [2]:
dat = pd.read_csv('used_cars_data.csv')
dat.head()

C:\Users\hibar\AppData\Local\Temp\ipykernel_9688\2568599977.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  dat = pd.read_csv('used_cars_data.csv')

,vin,back_legroom,bed,bed_height,bed_length,body_type,cabin,city,city_fuel_economy,combine_fuel_economy,...,transmission,transmission_display,trimId,trim_name,vehicle_damage_category,wheel_system,wheel_system_display,wheelbase,width,year
0,ZACNJABB5KPJ92081,35.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,Bayamon,NaN,NaN,...,A,9-Speed Automatic Overdrive,t83804,Latitude FWD,NaN,FWD,Front-Wheel Drive,101.2 in,79.6 in,2019
1,SALCJ2FX1LH858117,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020
2,JF1VA2M67G9829723,35.4 in,NaN,NaN,NaN,Sedan,NaN,Guaynabo,17.0,NaN,...,M,6-Speed Manual,t58994,Base,NaN,AWD,All-Wheel Drive,104.3 in,78.9 in,2016
3,SALRR2RV0L2433391,37.6 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,8-Speed Automatic Overdrive,t86074,V6 HSE AWD,NaN,AWD,All-Wheel Drive,115 in,87.4 in,2020
4,SALCJ2FXXLH862327,38.1 in,NaN,NaN,NaN,SUV / Crossover,NaN,San Juan,NaN,NaN,...,A,9-Speed Automatic Overdrive,t86759,S AWD,NaN,AWD,All-Wheel Drive,107.9 in,85.6 in,2020

In [23]:
na_counts = pd.DataFrame(dat.isna().sum())

In [24]:
na_counts = na_counts.reset_index()
na_counts

                   index        0
0                    vin        0
1           back_legroom   159269
2                    bed  2980472
3             bed_height  2570942
4             bed_length  2570942
..                   ...      ...
61          wheel_system   146732
62  wheel_system_display   146732
63             wheelbase   159269
64                 width   159269
65                  year        0

[66 rows x 2 columns]

In [25]:
na_counts['cols'] = na_counts['index']

In [28]:
cols_remove = (na_counts.sort_values(by = 0, ascending = False)).head(9)

In [43]:
#removed columns with 2 million missing
for i in (list(cols_remove.cols)):
    dat = dat.drop(i, axis = 1)

In [42]:
cols_remove.cols

60    vehicle_damage_category
9        combine_fuel_economy
30               is_certified
2                         bed
6                       cabin
33                  is_oemcpo
31                     is_cpo
3                  bed_height
4                  bed_length
Name: cols, dtype: object

In [45]:
dat.isna().sum()

vin                           0
back_legroom             159269
body_type                 13543
city                          0
city_fuel_economy        491285
daysonmarket                  0
dealer_zip                    0
description               77901
engine_cylinders         100581
engine_displacement      172386
engine_type              100581
exterior_color               26
fleet                   1426595
frame_damaged           1426595
franchise_dealer              0
franchise_make           572635
front_legroom            159269
fuel_tank_volume         159269
fuel_type                 82724
has_accidents           1426595
height                   159269
highway_fuel_economy     491285
horsepower               172386
interior_color              165
isCab                   1426595
is_new                        0
latitude                      0
length                   159269
listed_date                   0
listing_color                 0
listing_id                    0
longitude                     0
main_picture_url         369093
major_options            200048
make_name                     0
maximum_seating          159269
mileage                  144387
model_name                    0
owner_count             1517013
power                    481426
price                         0
salvage                 1426595
savings_amount                0
seller_rating             40872
sp_id                        96
sp_name                       0
theft_title             1426595
torque                   517793
transmission              64185
transmission_display      64185
trimId                   115827
trim_name                116294
wheel_system             146732
wheel_system_display     146732
wheelbase                159269
width                    159269
year                          0
dtype: int64

In [46]:
nonmissing_dat = dat.dropna()

In [47]:
nonmissing_dat.shape

(621616, 57)

In [48]:
data = nonmissing_dat.sample(n = 6000, random_state = 10)

In [ ]:
#test = nonmissing_dat.sample(n = 3000, random_state = 20)

In [51]:
data.shape

(6000, 57)

In [52]:
data.price.isna().sum()

0

In [53]:
data.to_csv('us_used_cars_final.csv', index = False)

In [55]:
data.dtypes

vin                      object
back_legroom             object
body_type                object
city                     object
city_fuel_economy       float64
daysonmarket              int64
dealer_zip               object
description              object
engine_cylinders         object
engine_displacement     float64
engine_type              object
exterior_color           object
fleet                    object
frame_damaged            object
franchise_dealer           bool
franchise_make           object
front_legroom            object
fuel_tank_volume         object
fuel_type                object
has_accidents            object
height                   object
highway_fuel_economy    float64
horsepower              float64
interior_color           object
isCab                    object
is_new                     bool
latitude                float64
length                   object
listed_date              object
listing_color            object
listing_id                int64
longitude               float64
main_picture_url         object
major_options            object
make_name                object
maximum_seating          object
mileage                 float64
model_name               object
owner_count             float64
power                    object
price                   float64
salvage                  object
savings_amount            int64
seller_rating           float64
sp_id                   float64
sp_name                  object
theft_title              object
torque                   object
transmission             object
transmission_display     object
trimId                   object
trim_name                object
wheel_system             object
wheel_system_display     object
wheelbase                object
width                    object
year                      int64
dtype: object

In [56]:
data.head()

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
2653463,5LMCJ2C97HUL71203,36.8 in,SUV / Crossover,Devine,21.0,40,78016,*We have 19 sources of financing and second ch...,I4,2000.0,...,"270 lb-ft @ 3,000 RPM",A,Automatic,t66989,Select FWD,FWD,Front-Wheel Drive,105.9 in,84.1 in,2017
1912149,1FM5K8D87HGE07214,39.5 in,SUV / Crossover,Buffalo,16.0,9,55313,We are open for business. Purchase your nex...,V6,3500.0,...,"255 lb-ft @ 4,000 RPM",A,6-Speed Automatic,t67141,XLT AWD,AWD,All-Wheel Drive,112.8 in,90.2 in,2017
1613127,1FMCU0GX6FUA14602,36.8 in,SUV / Crossover,Murfreesboro,23.0,30,37129,CARFAX One-Owner.THIS VEHICLE HAS GONE THROUGH...,I4,2500.0,...,"170 lb-ft @ 4,500 RPM",A,Automatic,t55391,SE FWD,FWD,Front-Wheel Drive,105.9 in,81.8 in,2015
2987274,WBA4W7C56JAB87837,33.7 in,Coupe,San Rafael,21.0,45,94901,FUEL EFFICIENT 32 MPG Hwy/21 MPG City! CARFAX ...,I6,3000.0,...,"330 lb-ft @ 1,380 RPM",A,8-Speed Automatic,t73244,440i Coupe RWD,RWD,Rear-Wheel Drive,110.6 in,79.4 in,2018
134975,SADCL2GX4KA397815,37.2 in,SUV / Crossover,Glen Cove,22.0,319,11542,Santorini Black 2019 Jaguar F-PACE 30t R-Sport...,I4,2000.0,...,"295 lb-ft @ 1,500 RPM",A,8-Speed Automatic,t83299,30t R-Sport AWD,AWD,All-Wheel Drive,113.1 in,85.6 in,2019

In [2]:
data.shape

NameError: name 'data' is not defined